### ISSUE TITLE
Builds incomplete wheel for SciPy because "File could not be mapped to an equivalent wheel directory"

### ISSUE THREAD

**Issue by mkoeppe** [FFY00/meson-python#127]
This is on gentoo with gentoo's python3.9. @rgommers 

https://github.com/mkoeppe/sage/runs/7659423834?check_suite_focus=true

```
e75b6879f2d8 /sage # cat logs/pkgs/scipy-1.9.0rc3.log 
[...]
  + meson install --destdir /sage/local/var/lib/sage/venv-python3.9/var/tmp/sage/build/scipy-1.9.0rc3/src/.mesonpy-cjaz4nzj/install
  WARNING Using heuristics to map files to wheel, this may result in incorrect locations
  WARNING File could not be mapped to an equivalent wheel directory: /sage/local/var/lib/sage/venv-python3.9/var/tmp/sage/build/scipy-1.9.0rc3/src/.mesonpy-cjaz4nzj/install/usr/lib/python-exec/python3.9/../../../lib/python3.9/site-packages/scipy/__config__.py (/usr/lib/python-exec/python3.9/../../../lib/python3.9/site-packages//scipy/__config__.py)
  WARNING File could not be mapped to an equivalent wheel directory: /sage/local/var/lib/sage/venv-python3.9/var/tmp/sage/build/scipy-1.9.0rc3/src/.mesonpy-cjaz4nzj/install/usr/lib/python-exec/python3.9/../../../lib/python3.9/site-packages/scipy/version.py (/usr/lib/python-exec/python3.9/../../../lib/python3.9/site-packages//scipy/version.py)
  WARNING File could not be mapped to an equivalent wheel directory: /sage/local/var/lib/sage/venv-python3.9/var/tmp/sage/build/scipy-1.9.0rc3/src/.mesonpy-cjaz4nzj/install/usr/lib/python-exec/python3.9/../../../lib/python3.9/site-packages/scipy/_lib/_ccallback_c.cpython-39-x86_64-linux-gnu.so ({moduledir_shared}/_ccallback_c.cpython-39-x86_64-linux-gnu.so)
  WARNING File could not be mapped to an equivalent wheel directory: /sage/local/var/lib/sage/venv-python3.9/var/tmp/sage/build/scipy-1.9.0rc3/src/.mesonpy-cjaz4nzj/install/usr/lib/python-exec/python3.9/../../../lib/python3.9/site-packages/scipy/_lib/_test_ccallback.cpython-39-x86_64-linux-gnu.so ({moduledir_shared}/_test_ccallback.cpython-39-x86_64-linux-gnu.so)
[...]
```

Ref: https://trac.sagemath.org/ticket/34081#comment:58

**Comment by rgommers** [comment]
Thanks @mkoeppe. This may have been fixed already. It looks like the versions in that CI log are:
```
[scipy-1.9.0rc3] successfully installed
 meson-0.62.2
meson_python-0.8.0
```
The meson-python `0.8.1` release contains gh-119, which fixes an issue in the heuristics code that the above warnings are about.

**Comment by mkoeppe** [comment]
Thanks for the pointer, I missed that 0.8.1 is out.

But the problem persists after upgrading to 0.8.1

**Comment by rgommers** [comment]
Hmm. The missing `//scipy/__config__.py` should definitely be gone after https://github.com/scipy/scipy/pull/16760, but that still needs a backport to scipy `1.9.1`.

There's a combination of little fixes in `scipy`, `meson-python` and `meson` that makes it a little tricky to figure out where exactly the problem is and what versions are needed to resolve it. Sorry for the trouble!

**Comment by eli-schwartz** [comment]
> Hmm. The missing `//scipy/__config__.py` should definitely be gone after [scipy/scipy#16760](https://github.com/scipy/scipy/pull/16760), but that still needs a backport to scipy `1.9.1`.

That PR is just a prerequisite for the little fix in `meson` that ensures all 4 of these files are mapped properly.

**Comment by rgommers** [comment]
SciPy 1.9.1 is out now, and it looks like there are no more `File could not be mapped` warnings left with Meson `main`. With `0.63.1` (latest release as of now) there are still a bunch of warnings like this:
```
WARNING Could not tell with certainty if this file was meant to be mapped to platlib, but it was used to calculate the ABI tag: /home/rgommers/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/scipy/_lib/_ccallback_c.cpython-310-x86_64-linux-gnu.so
```
So this will be resolved in Meson `0.64.0`, which based on release history is likely to arrive end of October. The PR that fixed it is https://github.com/mesonbuild/meson/pull/10652. Not sure if it will be backported to `0.63.2` @eli-schwartz?

**Comment by eli-schwartz** [comment]
Does this "WARNING" indicate an error building the wheel? The message seems to imply it falls back on heuristics which may work?

**Comment by rgommers** [comment]
Not necessarily indeed. Warnings for files like `lapack_routines.f` were there for a long time, but tons of warnings for Python extensions (which I still see with scipy 1.9.1 + meson-python 0.8.1 + meson 0.63.1) were some kind of regression.

Would be great if @mkoeppe could confirm though.

**Comment by mkoeppe** [comment]
No, still the same.

**Comment by mkoeppe** [comment]
I would be able to provide a CI for building with Python from various Linux distros if there's interest.

**Comment by rgommers** [comment]
Thanks @mkoeppe. 

More CI for cases where Linux distros do different things with their Python installs seems useful indeed. gh-76 tracks the need for a Debian/Ubuntu job. Your failing one seems to be using Gentoo. I'm not that familiar with it, any idea in what way that is different? And do you see the need for any other distros?

**Comment by mkoeppe** [comment]
That's #133 now

**Comment by eli-schwartz** [comment]
> Not sure if it will be backported to `0.63.2` @eli-schwartz?

That was released over the weekend without it (actually, the branch was cut before this discussion, I tried to mark it for backporting late Friday, but the release manager didn't notice and regenerate the release once the CI was fixed Saturday morning).

We'll see if it gets into a .3 release though.

**Comment by thesamesam** [comment]
Feel free to ping me if you need something from us re Gentoo.

**Comment by rgommers** [comment]
@mkoeppe https://github.com/scipy/scipy/pull/16969 should fix this I believe.

@thesamesam thanks. I don't think anything is needed from Gentoo, although I would recommend to make purelib and platlib point to the same directory for Gentoo Python installs (if you can do that without backwards compat impact - which may not be the case). Not doing that makes Gentoo susceptible to subtle bugs like this that don't show up on almost any other distro. purelib/platlib is an obsolete concept.

**Comment by mgorny** [comment]
> @thesamesam thanks. I don't think anything is needed from Gentoo, although I would recommend to make purelib and platlib point to the same directory for Gentoo Python installs (if you can do that without backwards compat impact - which may not be the case). Not doing that makes Gentoo susceptible to subtle bugs like this that don't show up on almost any other distro. purelib/platlib is an obsolete concept.

I'm not sure if I understand you correctly but they should be pointing to the same directory:

```pytb
In [1]: import sysconfig

In [2]: sysconfig.get_paths()
Out[2]: 
{'stdlib': '/usr/lib/python3.10',
 'platstdlib': '/usr/lib/python3.10',
 'purelib': '/usr/lib/python3.10/site-packages',
 'platlib': '/usr/lib/python3.10/site-packages',
 'include': '/usr/include/python3.10',
 'platinclude': '/usr/include/python3.10',
 'scripts': '/usr/bin',
 'data': '/usr'}
```

…or is this about something else? To the best of my knowledge, we never did the purelib/platlib split.

**Comment by rgommers** [comment]
Thanks for looking into that @mgorny. Okay, then I'm a little stumped as to why things were only breaking on Gentoo. We have CI now and a bunch of fixes for various little paper cuts, so we'll try to figure it out.

**Comment by mgorny** [comment]
Thanks. I'm afraid I can't offer much help right now but if you need me to quickly check something or run some mechanical task, I can do that.

**Comment by rgommers** [comment]
A bunch more fixes were merged, including for absolute paths in `intro-install_plan.json` with Meson 0.63.2. With the main/master version of `meson`, `meson-python` and `scipy` I'm ~99.x% sure this is fixed. WIth current released versions it probably isn't. We should get a `meson-python` release very soon (all pending PRs were merged), and a `scipy` 1.9.2 release with backports of the relevant build fixes within 1-2 weeks.

**Comment by eli-schwartz** [comment]
> We'll see if it gets into a .3 release though.

It's in the one we are cooking right now.

**Comment by mkoeppe** [comment]
The problem on gentoo persists with meson 0.63.3, meson-python 0.10.0, scipy 1.9.2

**Comment by rgommers** [comment]
Thanks for checking @mkoeppe. We'll need to prioritize this then, reproducing the issue in Docker and debugging it. I'll make a plan for this.

**Comment by mkoeppe** [comment]
In case you haven't seen this, you can pull the failing build from my CI as a Docker image, for example
```
docker run -it ghcr.io/mkoeppe/sage/sage-docker-gentoo-python3.9-standard-with-targets:9.5-88594-g502f9e71fe-failed bash
```
or 
```
docker run -it ghcr.io/ffy00/meson-python/meson-python-sage-docker-gentoo-python3.9-standard-develop-with-targets:9.8.beta1-149-g99de8018b1-dirty-failed bash
```
(from https://github.com/FFY00/meson-python/actions/runs/3205923912/jobs/5239063506)

**Comment by FFY00** [comment]
In that run, we are getting an absolute path from Meson, which shouldn't be happening in 0.63.3.

And from the log, it appears we are picking 0.63.1.

```
  [meson_python-git]   The Meson build system
  [meson_python-git]   Version: 0.63.1
  [meson_python-git]   Source dir: /sage/local/var/lib/sage/venv-python3.9/var/tmp/sage/build/meson_python-git/src/docs/examples/spam
  [meson_python-git]   Build dir: /sage/local/var/lib/sage/venv-python3.9/var/tmp/sage/build/meson_python-git/src/docs/examples/spam/build
  [meson_python-git]   Build type: native build
  [meson_python-git]   Project name: spam
  [meson_python-git]   Project version: undefined
  [meson_python-git]   C compiler for the host machine: gcc (gcc 11.3.0 "gcc (Gentoo 11.3.0 p4) 11.3.0")
  [meson_python-git]   C linker for the host machine: gcc ld.bfd 2.38
  [meson_python-git]   Host machine cpu family: x86_64
  [meson_python-git]   Host machine cpu: x86_64
  [meson_python-git]   Program python found: YES (/sage/local/var/lib/sage/venv-python3.9/bin/python3)
  [meson_python-git]   Found pkg-config: /usr/bin/pkg-config (1.8.0)
  [meson_python-git]   Build targets in project: 1
  [meson_python-git]   
  [meson_python-git]   spam undefined
  [meson_python-git]   
  [meson_python-git]     User defined options
  [meson_python-git]       Native files: /sage/local/var/lib/sage/venv-python3.9/var/tmp/sage/build/meson_python-git/src/docs/examples/spam/.mesonpy-native-file.ini
  [meson_python-git]       debug       : false
  [meson_python-git]       optimization: 2
  [meson_python-git]       prefix      : /usr/lib/python-exec/python3.9/../../..
  [meson_python-git]   
  [meson_python-git]   Found ninja-1.11.0 at /usr/bin/ninja
```

So I wonder what is going wrong there.

**Comment by mkoeppe** [comment]
That ran 6 days ago, i.e., before I updated meson in https://trac.sagemath.org/ticket/34081#comment:97

**Comment by mkoeppe** [comment]
In a more recent run, for example, https://github.com/FFY00/meson-python/actions/runs/3244203563/jobs/5320152605, you'll see that meson 0.63.3 is in use.
Each run shows the available Docker images in the output section titled "List docker images".

**Comment by FFY00** [comment]
Right, that's a different failure though, from a test that is a bit flaky, I haven't figured out why yet. All files seem to map as expected, no heuristics code paths are triggered.

I think what you were running into originally has been fixed already.

**Comment by mkoeppe** [comment]
Yes, the `ImportError: dynamic module does not define module export function` only shows up in the meson-python testsuite and does not seem to have an effect on building scipy. 

But the problem reported here on this Issue, on gentoo, is still present and prevents us from building scipy

**Comment by mkoeppe** [comment]
I can't make much sense of some of the meson-python test suite errors in https://github.com/FFY00/meson-python/actions/runs/3244203563/jobs/5320152432 such as 
```
Run-time dependency python3 found: NO (tried pkgconfig and sysconfig)

../../meson.build:11:0: ERROR: Dependency "python3" not found, tried pkgconfig and sysconfig
```
These failures do look different from the originally reported problem.

**Comment by mkoeppe** [comment]
> The problem on gentoo persists with meson 0.63.3, meson-python 0.10.0, scipy 1.9.2

I have to retract this claim. I made a mistake when testing it, sorry for the noise! It builds correctly on gentoo (for example https://github.com/mkoeppe/sage/actions/runs/3239323923/jobs/5325838781).
